default: &default
  adapter: mysql2
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: cdm_development

test:
  <<: *default
  database: cdm_development_test

production:
  <<: *default
  database: cdm_development_production
  username: production
  password: bs36613hVxUgA20i

