default: &default
  adapter: mysql2
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: cdm_development

test:
  <<: *default
  database: cdm_test

production:
  <<: *default
  database: cdm_production
  username: root
  password: root

