yourub_defaults: &yourub_defaults
  developer_key: 'AIzaSyD72H6xcPcV9-gwxGJMTS67mDF5MLnnU4I'
  youtube_api_service_name: 'youtube'
  youtube_api_version: 'v3'
  application_name: "cdm"
  application_version: 1.0
  log_level: 3

development:
  <<: *yourub_defaults

production:
  <<: *yourub_defaults

test:
  <<: *yourub_defaults
